{
 "title": "Artifactory",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "File Upload Histogram",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(artifactory_http_requests_duration_seconds_bucket{job=\"mdcap-artifactory\", method=\"PUT\", status=\"200\"})) by (le)"
    }
   ]
  },
  {
   "title": "File download histogram",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(artifactory_http_requests_duration_seconds_bucket{job=\"mdcap-artifactory\", endpoint=\"/{filename:..*}\", method=\"GET\", status=\"200\"}[30m])) by (le)"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "artifactory_http_requests_total{job=\"mdcap-artifactory\"}",
     "legendFormat": "{{  method }} {{ endpoint }} {{ status }}"
    }
   ]
  }
 ]
}