{
 "title": "Engine",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total CPU seconds",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"mdcap-engine\"}"
    }
   ]
  },
  {
   "title": "Resident Memory %",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sanic_mem_rss_perc{job=\"mdcap-engine\"} * 100 "
    },
    {}
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_open_fds{job=\"mdcap-engine\"}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"mdcap-engine\"}"
    },
    {}
   ]
  },
  {
   "title": "Resident Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"mdcap-engine\"}"
    },
    {
     "expr": "sanic_mem_rss_bytes{job=\"mdcap-engine\"}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sum(sanic_request_count_total{job=\"mdcap-engine\"}[30m]))"
    }
   ]
  }
 ]
}