{
 "title": "Logstore",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total CPU Seconds",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"mdcap-logstore\"}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_open_fds{job=\"mdcap-logstore\"}"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"mdcap-logstore\"}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"mdcap-logstore\"}"
    }
   ]
  },
  {
   "title": "Exception Counters",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(aiohttp_exceptions_total{job=\"mdcap-logstore\"}) by (exception_type)",
     "legendFormat": "{{ exception_type }}"
    }
   ]
  },
  {
   "title": "Number of logs stored",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(aiohttp_requests_total{job=\"mdcap-logstore\", method=\"POST\",path_template!=\"__not_matched__\"})"
    }
   ]
  },
  {
   "title": "Logs stored duration histogram",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aiohttp_request_duration_seconds_bucket{job=\"mdcap-logstore\", method=\"POST\", status_code=\"200\"}[30m])) by (le)"
    }
   ]
  }
 ]
}