{
 "title": "Patroni",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "scope",
    "query": "label_values(patroni_patroni_info, scope)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current timeline",
   "type": "gauge",
   "description": "This value needs to be the same for every instance, otherwise replication won't work",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "patroni_postgresql_timeline * ON (instance, job) group_left(scope, role, state, version) (patroni_patroni_info{scope=~\"$scope\"})",
     "legendFormat": "{{role}} / {{state}} / {{version}}"
    }
   ]
  },
  {
   "title": "Master / replica difference",
   "type": "graph",
   "description": "Beware that this is affected by scrape times - higher scrape times lead to higher differences.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(patroni_xlog_replayed_location * ON (instance, job) group_left(scope) (patroni_patroni_info{scope=~\"$scope\"}) )\n- ON(scope) group_left(job)\n(patroni_xlog_location * ON (instance, job) group_left(scope) (patroni_patroni_info{scope=~\"$scope\"}) )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Paused nodes",
   "type": "graph",
   "description": "Only shows paused instances. This should normally say \"No data points\"",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "patroni_patroni_pause == 1", "legendFormat": "{{instance}} / Patroni paused" },
    { "expr": "patroni_xlog_paused == 1", "legendFormat": "{{instance}} / xlog paused" }
   ]
  },
  {
   "title": "Replication Summary",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "patroni_replication_info",
     "legendFormat": "{{sync_state}} / {{state}}  / {{ usename }}"
    }
   ]
  }
 ]
}