apiVersion: 1
providers:
  - name: 'mdcap'
    folder: 'MDCAP'
    orgId: 1
    type: file
    disableDeletion: true
    updateIntervalSeconds: 10
    allowUiUpdates: true
    options:
      path: /etc/grafana/provisioning/dashboards
      foldersFromFilesStructure: true