{{/*
Copyright (C) 2021 Robin.io All Rights Reserved.
*/}}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-key-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ (.Files.Glob "scripts/certs/key.pem").AsSecrets | nindent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-cert-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ (.Files.Glob "scripts/certs/cert.pem").AsSecrets | nindent 2 }}
---
{{ if .Values.imageCredentials.registry }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-imagepull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}

