{{/*
Copyright (C) 2021 Robin.io All Rights Reserved.
*/}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-playground-entrypoint-configmap
  namespace: {{ .Release.Namespace }}
data:
  {{ (.Files.Glob "scripts/playground-entrypoint.sh").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-playground-mdcapcli
  namespace: {{ .Release.Namespace }}
data:
  {{ (.Files.Glob "scripts/mdcapcli/mdcap.py").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-playground-env
  namespace: {{ .Release.Namespace }}
data:
  MDCAP_SSL_CERTS_DIR: /etc/mdcap/certs
  MDCAP_EVTSRV_HOST: {{ .Release.Name }}-eventserver.{{ .Release.Namespace }}.svc.cluster.local
  POD_NAME: {{ .Release.Name }}-playground
  MDCAP_DEFAULT_CONTEXT: "https://{{ .Release.Name }}-engine.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.engine.rorcPort }}"
  MDCAP_LOG_HOST: {{ .Release.Name }}-logstore.{{ .Release.Namespace }}.svc.cluster.local
  MDCAP_ARTIFACTORY_HOST: {{ .Release.Name }}-artifactory.{{ .Release.Namespace }}.svc.cluster.local
  MDCAP_ENGINE_HOST: {{ .Release.Name }}-engine.{{ .Release.Namespace }}.svc.cluster.local
  POD_NS: {{ .Release.Namespace }}
  MDCAP_LOG_URL: https://{{ .Release.Name }}-logstore.{{ .Release.Namespace }}.svc.cluster.local:8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: {{ .Release.Name }}-playground-depl
    release: {{ .Release.Name }}
    app: {{ .Release.Name }}-playground
  name: {{ template "playground.fullname" . }}
{{- if .Values.playground.annotations }}
  annotations:
{{ toYaml .Values.playground.annotations | indent 4 }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-playground
  strategy:
    type: RollingUpdate
    rollingUpdate:
    {{- if .Release.IsUpgrade }}
      maxUnavailable: 1
    {{- else }}
      maxUnavailable: 30%
    {{- end }}
      maxSurge: 1
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9100"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
{{- if .Values.playground.annotations }}
{{ toYaml .Values.playground.annotations | indent 8 }}
{{- end }}
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}-playground
        release: {{ .Release.Name }}
        app: {{ .Release.Name }}-playground
      name: {{ .Release.Name }}-playground
      namespace: {{ .Release.Namespace }}
    spec:
{{ if .Values.imageCredentials.registry }}
      imagePullSecrets:
        - name:  {{ .Release.Name }}-imagepull-secret
{{ end }}
{{ if .Values.playground.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.playground.nodeSelector | indent 8 }}
{{ end }}
      containers:
      - command:
        - /scripts/playground-entrypoint.sh
        - /bin/bash
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-playground-env
        image: "{{ .Values.playground.image.repository }}:{{ .Values.playground.image.tag }}"
        imagePullPolicy: "{{ .Values.playground.image.pullPolicy }}"
        name: {{ .Release.Name }}-playground
        livenessProbe:
{{ toYaml .Values.playground.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.playground.readinessProbe | indent 10 }}
        resources:
{{ toYaml .Values.playground.resources | indent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /scripts/playground-entrypoint.sh
          name: entrypoint-script
          subPath: playground-entrypoint.sh
        - mountPath: /etc/mdcap/certs/cert.pem
          name: cert-secret
          readOnly: true
          subPath: cert.pem
        - mountPath: /etc/mdcap/certs/key.pem
          name: key-secret
          readOnly: true
          subPath: key.pem
        - mountPath: /.robin/scripts/app/mdcapcli/mdcap.py
          name: mdcapcli-configmap
          subPath: mdcap.py
        - mountPath: "{{ .Values.playground.persistentVolume.mountPath }}"
          name: {{ .Release.Name }}-playground-volume-data
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      hostname: {{ .Release.Name }}-playground-01
      priority: 0
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - name: entrypoint-script
          configMap:
            name: {{ .Release.Name }}-playground-entrypoint-configmap
            defaultMode: 0755
        - name: cert-secret
          secret:
            secretName: {{ .Release.Name }}-cert-secret
            defaultMode: 0420
        - name: key-secret
          secret:
            secretName: {{ .Release.Name }}-key-secret
            defaultMode: 0420
        - name: mdcapcli-configmap
          configMap:
            name: {{ .Release.Name }}-playground-mdcapcli
            defaultMode: 0755
        - name: {{ .Release.Name }}-playground-volume-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-playground-pvc-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-playground-pvc-data
{{- if .Values.playground.persistentVolume.annotations }}
  annotations:
{{ toYaml .Values.playground.persistentVolume.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.playground.persistentVolume.accessMode }}
  storageClassName: {{ include "playground.storageclass.name" . }} 
  resources:
    requests:
      storage: {{ .Values.playground.persistentVolume.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-playground
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: {{ .Release.Name }}-playground
    port: 65535
    protocol: UDP
    targetPort: 65535
  selector:
    app: {{ .Release.Name }}-playground
  type: ClusterIP
  clusterIP: None