{{/*
Copyright (C) 2021 Robin.io All Rights Reserved.
*/}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-post-upgrade"
  namespace: {{ .Release.Namespace }}
  labels:
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
    spec:
{{ if .Values.imageCredentials.registry }}
      imagePullSecrets:
        - name:  {{ .Release.Name }}-imagepull-secret
{{ end }}
      restartPolicy: Never
      containers:
      - name: dbupgrade
        image: {{ .Values.dbupgrade.image.repository }}:{{ .Values.dbupgrade.image.tag }}
        env:
        - name: MDCAP_ENGINE_URL
          value: https://{{ .Release.Name }}-engine.{{ .Release.Namespace }}.svc.cluster.local:8000
        - name: MDCAP_VERSION_NEW
          value: {{ .Chart.Version | quote }}
        - name: MDCAP_DB_USER
          value: {{ required "A value must be entered for .Values.postgres.User" .Values.postgres.user }}
        - name: MDCAP_DB_PASSWORD
          value: {{ required "A value must be entered for .Values.postgres.Password" .Values.postgres.password }}
        - name: MDCAP_DB_SERVER
          value: {{ required "A value must be entered for .Values.postgres.Server" .Values.postgres.server }}
        - name: MDCAP_DB_PORT
          value: {{ required "A value must be entered for .Values.postgres.Port" .Values.postgres.port | quote }}
        - name: MDCAP_WORKER_IMG
          value: "{{ .Values.taskrunner.image.repository }}:{{ .Values.taskrunner.image.tag }}"
        - name: MDCAP_BUILD_NUMBER
          value: "{{ .Values.buildNumber }}"
        command:
        - /dbupgrade
        - postupgrade
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 512Mi

